<?xml version="1.0" encoding="utf-8"?><Database Name="BazaRelacyjna" Class="BazaRelacyjnaDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=FILIPBE\CINDALNET;Initial Catalog=BazaRelacyjna;User ID=sa" SettingsObjectName="Cindalnet.SQLBot.Properties.Settings" SettingsPropertyName="BazaRelacyjnaConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.vSQLBotFields" Member="vSQLBotFields">
    <Type Name="vSQLBotFields">
      <Column Name="TableNameSQL" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TableName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TableDescription" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="FieldNameSQL" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FieldName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FieldType" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FieldKind" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FieldDescription" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Dzialy" Member="Dzialy">
    <Type Name="Dzialy">
      <Column Name="IdDzialu" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nazwa" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Association Name="Dzialy_Osoby" Member="Osoby" ThisKey="IdDzialu" OtherKey="IdDzialu" Type="Osoby" />
    </Type>
  </Table>
  <Table Name="dbo.Faktury" Member="Faktury">
    <Type Name="Faktury">
      <Column Name="IdFaktury" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdOsoby" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdKlienta" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Data" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Faktury_Transakcje" Member="Transakcje" ThisKey="IdFaktury" OtherKey="IdFaktury" Type="Transakcje" />
      <Association Name="Klienci_Faktury" Member="Klienci" ThisKey="IdKlienta" OtherKey="IdKlienta" Type="Klienci" IsForeignKey="true" />
      <Association Name="Osoby_Faktury" Member="Osoby" ThisKey="IdOsoby" OtherKey="IdOsoby" Type="Osoby" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Kategorie" Member="Kategorie">
    <Type Name="Kategorie">
      <Column Name="IdKategorii" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NazwaKategorii" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Kategorie_Towar" Member="Towar" ThisKey="IdKategorii" OtherKey="IdKategorii" Type="Towar" />
    </Type>
  </Table>
  <Table Name="dbo.Klienci" Member="Klienci">
    <Type Name="Klienci">
      <Column Name="IdKlienta" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdMiasta" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Nazwisko" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="Imie" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Association Name="Klienci_Faktury" Member="Faktury" ThisKey="IdKlienta" OtherKey="IdKlienta" Type="Faktury" />
      <Association Name="Miasta_Klienci" Member="Miasta" ThisKey="IdMiasta" OtherKey="IdMiasta" Type="Miasta" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Miasta" Member="Miasta">
    <Type Name="Miasta">
      <Column Name="IdMiasta" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IdWojewodztwa" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Miasto" Type="System.String" DbType="NVarChar(33)" CanBeNull="true" />
      <Association Name="Miasta_Klienci" Member="Klienci" ThisKey="IdMiasta" OtherKey="IdMiasta" Type="Klienci" />
      <Association Name="Miasta_Producenci" Member="Producenci" ThisKey="IdMiasta" OtherKey="IdMiasta" Type="Producenci" />
      <Association Name="Wojewodztwa_Miasta" Member="Wojewodztwa" ThisKey="IdWojewodztwa" OtherKey="IdWojewodztwa" Type="Wojewodztwa" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Osoby" Member="Osoby">
    <Type Name="Osoby">
      <Column Name="IdOsoby" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdDzialu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Nazwisko" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="Imie" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="RokUrodz" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Wzrost" Type="System.Decimal" DbType="Decimal(3,2)" CanBeNull="true" />
      <Column Name="DataZatr" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IdSzefa" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Osoby_Faktury" Member="Faktury" ThisKey="IdOsoby" OtherKey="IdOsoby" Type="Faktury" />
      <Association Name="Osoby_Zarobki" Member="Zarobki" ThisKey="IdOsoby" OtherKey="IdOsoby" Type="Zarobki" />
      <Association Name="Dzialy_Osoby" Member="Dzialy" ThisKey="IdDzialu" OtherKey="IdDzialu" Type="Dzialy" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Producenci" Member="Producenci">
    <Type Name="Producenci">
      <Column Name="IdProducenta" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NazwaProducenta" Type="System.String" DbType="VarChar(33)" CanBeNull="true" />
      <Column Name="IdMiasta" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Producenci_Towar" Member="Towar" ThisKey="IdProducenta" OtherKey="IdProducenta" Type="Towar" />
      <Association Name="Miasta_Producenci" Member="Miasta" ThisKey="IdMiasta" OtherKey="IdMiasta" Type="Miasta" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SQLBot_Field" Member="SQLBot_Field">
    <Type Name="SQLBot_Field">
      <Column Name="sqlf_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="sqlf_Table" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="sqlf_SQLColumnName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="sqlf_ColumnName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="sqlf_Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="sqlf_Kind" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="sqlf_Description" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Association Name="SQLBot_Field_SQLBot_TableDefault" Member="SQLBot_TableDefault" ThisKey="sqlf_ID" OtherKey="sqld_SQLColumn" Type="SQLBot_TableDefault" />
      <Association Name="SQLBot_FieldType_SQLBot_Field" Member="SQLBot_FieldType" ThisKey="sqlf_Type" OtherKey="sqlft_ID" Type="SQLBot_FieldType" IsForeignKey="true" />
      <Association Name="SQLBot_Table_SQLBot_Field" Member="SQLBot_Table" ThisKey="sqlf_Table" OtherKey="sqlt_ID" Type="SQLBot_Table" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SQLBot_FieldType" Member="SQLBot_FieldType">
    <Type Name="SQLBot_FieldType">
      <Column Name="sqlft_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="sqlft_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="SQLBot_FieldType_SQLBot_Field" Member="SQLBot_Field" ThisKey="sqlft_ID" OtherKey="sqlf_Type" Type="SQLBot_Field" />
    </Type>
  </Table>
  <Table Name="dbo.SQLBot_Table" Member="SQLBot_Table">
    <Type Name="SQLBot_Table">
      <Column Name="sqlt_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="sqlt_SQLName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="sqlt_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="sqlt_Description" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Association Name="SQLBot_Table_SQLBot_Field" Member="SQLBot_Field" ThisKey="sqlt_ID" OtherKey="sqlf_Table" Type="SQLBot_Field" />
      <Association Name="SQLBot_Table_SQLBot_TableJoin" Member="SQLBot_TableJoin" ThisKey="sqlt_ID" OtherKey="sqltj_Table1" Type="SQLBot_TableJoin" />
      <Association Name="SQLBot_Table_SQLBot_TableJoin1" Member="SQLBot_TableJoin1" ThisKey="sqlt_ID" OtherKey="sqltj_Table2" Type="SQLBot_TableJoin" />
      <Association Name="SQLBot_Table_SQLBot_TableDefault" Member="SQLBot_TableDefault" ThisKey="sqlt_ID" OtherKey="sqld_Table" Type="SQLBot_TableDefault" />
    </Type>
  </Table>
  <Table Name="dbo.Towar" Member="Towar">
    <Type Name="Towar">
      <Column Name="IdTowaru" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdKategorii" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdProducenta" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NazwaTowaru" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Cena" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="CenaZakupu" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="Towar_Transakcje" Member="Transakcje" ThisKey="IdTowaru" OtherKey="IdTowaru" Type="Transakcje" />
      <Association Name="Kategorie_Towar" Member="Kategorie" ThisKey="IdKategorii" OtherKey="IdKategorii" Type="Kategorie" IsForeignKey="true" />
      <Association Name="Producenci_Towar" Member="Producenci" ThisKey="IdProducenta" OtherKey="IdProducenta" Type="Producenci" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Transakcje" Member="Transakcje">
    <Type Name="Transakcje">
      <Column Name="IdTransakcji" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdFaktury" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdTowaru" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="szt" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Faktury_Transakcje" Member="Faktury" ThisKey="IdFaktury" OtherKey="IdFaktury" Type="Faktury" IsForeignKey="true" />
      <Association Name="Towar_Transakcje" Member="Towar" ThisKey="IdTowaru" OtherKey="IdTowaru" Type="Towar" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Wojewodztwa" Member="Wojewodztwa">
    <Type Name="Wojewodztwa">
      <Column Name="IdWojewodztwa" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Wojewodztwo" Type="System.String" DbType="NVarChar(55)" CanBeNull="true" />
      <Association Name="Wojewodztwa_Miasta" Member="Miasta" ThisKey="IdWojewodztwa" OtherKey="IdWojewodztwa" Type="Miasta" />
    </Type>
  </Table>
  <Table Name="dbo.Zarobki" Member="Zarobki">
    <Type Name="Zarobki">
      <Column Name="IdZarobku" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdOsoby" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Brutto" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="DataWyplaty" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Osoby_Zarobki" Member="Osoby" ThisKey="IdOsoby" OtherKey="IdOsoby" Type="Osoby" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SQLBot_TableJoin" Member="SQLBot_TableJoin">
    <Type Name="SQLBot_TableJoin">
      <Column Name="sqltj_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="sqltj_Table1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="sqltj_Table2" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="sqltj_Join" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="SQLBot_Table_SQLBot_TableJoin" Member="SQLBot_Table" ThisKey="sqltj_Table1" OtherKey="sqlt_ID" Type="SQLBot_Table" IsForeignKey="true" />
      <Association Name="SQLBot_Table_SQLBot_TableJoin1" Member="SQLBot_Table1" ThisKey="sqltj_Table2" OtherKey="sqlt_ID" Type="SQLBot_Table" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.vSQLBotTableJoins" Member="vSQLBotTableJoins">
    <Type Name="vSQLBotTableJoins">
      <Column Name="Table1NameSQL" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Table1Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Table2NameSQL" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Table2Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TableJoin" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.SQLBot_TableDefault" Member="SQLBot_TableDefault">
    <Type Name="SQLBot_TableDefault">
      <Column Name="sqld_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="sqld_Table" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="sqld_SQLColumn" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="SQLBot_Field_SQLBot_TableDefault" Member="SQLBot_Field" ThisKey="sqld_SQLColumn" OtherKey="sqlf_ID" Type="SQLBot_Field" IsForeignKey="true" />
      <Association Name="SQLBot_Table_SQLBot_TableDefault" Member="SQLBot_Table" ThisKey="sqld_Table" OtherKey="sqlt_ID" Type="SQLBot_Table" IsForeignKey="true" />
    </Type>
  </Table>
</Database>