<?xml version="1.0" encoding="utf-8"?><Database Name="cdn_tramwaje" Class="TramwajeDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=FILIPBE\CINDALNET;Initial Catalog=cdn_tramwaje;User ID=sa" SettingsObjectName="Cindalnet.SQLBot.Properties.Settings" SettingsPropertyName="cdn_tramwajeConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Linie" Member="Linies">
    <Type Name="Linie">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nazwa" Type="System.String" DbType="NChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Typ" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Association Name="Linie_WariantTrasy" Member="WariantTrasies" ThisKey="Id" OtherKey="LiniaId" Type="WariantTrasy" />
    </Type>
  </Table>
  <Table Name="dbo.Przyjazd" Member="Przyjazds">
    <Type Name="Przyjazd">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PrzystanekId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Dzień" Type="System.String" DbType="NChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Godzina" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Minuta" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Przystanek_Przyjazd" Member="Przystanek" ThisKey="PrzystanekId" OtherKey="Id" Type="Przystanek" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Przystanek" Member="Przystaneks">
    <Type Name="Przystanek">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="WariantId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nazwa" Type="System.String" DbType="NChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Ulica" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Association Name="Przystanek_Przyjazd" Member="Przyjazds" ThisKey="Id" OtherKey="PrzystanekId" Type="Przyjazd" />
      <Association Name="WariantTrasy_Przystanek" Member="WariantTrasy" ThisKey="WariantId" OtherKey="Id" Type="WariantTrasy" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.WariantTrasy" Member="WariantTrasies">
    <Type Name="WariantTrasy">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LiniaId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nazwa" Type="System.String" DbType="NChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Start" Type="System.String" DbType="NChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Koniec" Type="System.String" DbType="NChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="WariantTrasy_Przystanek" Member="Przystaneks" ThisKey="Id" OtherKey="WariantId" Type="Przystanek" />
      <Association Name="Linie_WariantTrasy" Member="Linie" ThisKey="LiniaId" OtherKey="Id" Type="Linie" IsForeignKey="true" />
    </Type>
  </Table>
</Database>